/**
 * VS Code Commands
 */
import * as vscode from 'vscode'
import { VibeDevToolsProvider, generateResponse, parseFiles } from './VibeDevToolsView'
import * as path from 'path'
import * as fs from 'fs'

export function registerCommands(context: vscode.ExtensionContext, provider: VibeDevToolsProvider) {

  // Open VibeDevTools sidebar
  context.subscriptions.push(
    vscode.commands.registerCommand('uniadapter-vibe-devtools.open', () => {
      vscode.commands.executeCommand('uniadapter-vibe-devtools.view.focus')
    })
  )

  // Quick generate from command palette
  context.subscriptions.push(
    vscode.commands.registerCommand('uniadapter-vibe-devtools.generate', async () => {
      const input = await vscode.window.showInputBox({
        prompt: 'VibeEngine: 描述你想要的小程序页面',
        placeHolder: '例如：帮我做一个商品详情页，包含轮播图、SKU、加购按钮',
      })
      if (!input) return

      const config = vscode.workspace.getConfiguration('uniadapter-vibe-devtools')
      const platform = config.get<string>('defaultPlatform', 'weapp')

      vscode.window.showInformationMessage('VibeEngine: 正在生成...')

      const response = generateResponse(input, platform)
      const files = parseFiles(response)

      if (files.length === 0) {
        vscode.window.showInformationMessage('VibeEngine: 未识别到文件')
        return
      }

      const selected = await vscode.window.showQuickPick(
        files.map(f => ({ label: '📄 ' + f.filename, fn: f })),
        { placeHolder: '选择要创建的文件' }
      )

      if (!selected) return

      const folder = vscode.workspace.workspaceFolders?.[0]
      if (!folder) { vscode.window.showWarningMessage('请先打开工作区'); return }

      const fp = path.join(folder.uri.fsPath, selected.fn.filename)
      const dir = path.dirname(fp)
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(fp, selected.fn.content, 'utf-8')
      const doc = await vscode.workspace.openTextDocument(fp)
      await vscode.window.showTextDocument(doc, { preview: false })
      vscode.window.showInformationMessage('VibeEngine: 已创建 ' + selected.fn.filename)
    })
  )

  // Insert component
  context.subscriptions.push(
    vscode.commands.registerCommand('uniadapter-vibe-devtools.insertComponent', async (name: string) => {
      const folder = vscode.workspace.workspaceFolders?.[0]
      if (!folder) { vscode.window.showWarningMessage('请先打开工作区'); return }

      const compCode = `// ${name} 组件
// Generated by UniAdapter VibeDevTools

Component({
  properties: {
    variant: { type: String, value: 'primary' },
    size: { type: String, value: 'medium' },
    disabled: { type: Boolean, value: false },
    loading: { type: Boolean, value: false },
  },

  data: {},

  methods: {
    onTap() {
      if (this.data.disabled || this.data.loading) return
      this.triggerEvent('click')
    },
  },
})
`

      const compsDir = path.join(folder.uri.fsPath, 'components')
      if (!fs.existsSync(compsDir)) fs.mkdirSync(compsDir, { recursive: true })
      const fp = path.join(compsDir, name + '.ts')
      fs.writeFileSync(fp, compCode, 'utf-8')
      const doc = await vscode.workspace.openTextDocument(fp)
      await vscode.window.showTextDocument(doc, { preview: false })
      vscode.window.showInformationMessage('VibeDevTools: 已创建 components/' + name + '.ts')
    })
  )

  // Switch platform
  context.subscriptions.push(
    vscode.commands.registerCommand('uniadapter-vibe-devtools.switchPlatform', async () => {
      const platforms = ['weapp', 'alipay', 'douyin', 'h5']
      const labels = ['💚 微信小程序', '🔵 支付宝小程序', '🎵 抖音小程序', '🌐 H5 / Web']
      const selected = await vscode.window.showQuickPick(
        labels.map((l, i) => ({ label: l, value: platforms[i] })),
        { placeHolder: '选择目标平台' }
      )
      if (!selected) return
      const config = vscode.workspace.getConfiguration('uniadapter-vibe-devtools')
      await config.update('defaultPlatform', selected.value, vscode.ConfigurationTarget.Workspace)
      vscode.window.showInformationMessage('VibeDevTools: 平台已切换为 ' + selected.label)
    })
  )
}
